src/Entity/Event.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use App\Controller\CompanyController;
use App\Entity\Trait\SlugTrait;
use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: EventRepository::class)]
#[ApiResource(

    operations: [

        new Get(
            uriTemplate: '/{id}/events',
            controller: CompanyController::class,
            name: 'app_event'
        ),

    ],
    normalizationContext: ['groups' => ['read:events']])]

class Event
{
    use SlugTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['read:events'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:events'])]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['read:events'])]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['read:events'])]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    #[Groups(['read:events'])]
    private ?\DateTimeInterface $start_time = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    #[Groups(['read:events'])]
    private ?\DateTimeInterface $end_time = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:events'])]
    private ?string $display_time_period = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:events'])]
    private ?string $theme = null;

    #[ORM\Column(length: 500)]
    #[Groups(['read:events'])]
    private ?string $image = null;

    #[ORM\Column(length: 500)]
    #[Groups(['read:events'])]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeInterface $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTimeInterface $end_time): static
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getDisplayTimePeriod(): ?string
    {
        return $this->display_time_period;
    }

    public function setDisplayTimePeriod(string $display_time_period): static
    {
        $this->display_time_period = $display_time_period;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): static
    {
        $this->theme = $theme;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\Post;
use App\Controller\ProductController;
use App\Repository\ProductRepository;
use App\Entity\Trait\SlugTrait;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[ApiResource(

    operations: [

    new Get(
        uriTemplate: '/{id}/products',
        controller: ProductController::class,
        name: 'app_product'
    ),
        new Post(
            uriTemplate: '/order',
            controller: ProductController::class,
            name: 'app_order'
        ),

],
    normalizationContext: ['groups' => ['read:products']])]

class Product
{
    use SlugTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['read:products'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le nom du produit ne peut pas être vide')]
    #[Groups(['read:products'])]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:products'])]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:products'])]
    private ?string $category = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:products'])]
    private ?string $style = null;

    #[ORM\Column(length: 500)]
    #[Groups(['read:products'])]
    private ?string $customer_description = null;

    #[ORM\Column(length: 600)]
    #[Groups(['read:products'])]
    private ?string $employee_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['read:products'])]
    private ?string $degree_of_alcohol = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:products'])]
    private ?string $origin = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read:products'])]
    private ?string $capacity = null;

    #[ORM\Column]
    #[Groups(['read:products'])]
    private ?int $price = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['read:products'])]
    private ?int $promotion = null;

    #[ORM\Column]
    #[Groups(['read:products'])]
    private ?int $totalPrice = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero(message: 'Le stock ne peut pas être négatif')]
    #[Groups(['read:products'])]
    private ?int $stock = null;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero(message: 'Le seuil de réapprovisionnement ne peut pas être négatif')]
    #[Groups(['read:products'])]
    private ?int $threshold = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['read:products'])]
    private ?string $label = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getStyle(): ?string
    {
        return $this->style;
    }

    public function setStyle(string $style): static
    {
        $this->style = $style;

        return $this;
    }

    public function getCustomerDescription(): ?string
    {
        return $this->customer_description;
    }

    public function setCustomerDescription(string $customer_description): static
    {
        $this->customer_description = $customer_description;

        return $this;
    }

    public function getEmployeeDescription(): ?string
    {
        return $this->employee_description;
    }

    public function setEmployeeDescription(string $employee_description): static
    {
        $this->employee_description = $employee_description;

        return $this;
    }

    public function getDegreeOfAlcohol(): ?string
    {
        return $this->degree_of_alcohol;
    }

    public function setDegreeOfAlcohol(string $degree_of_alcohol): static
    {
        $this->degree_of_alcohol = $degree_of_alcohol;

        return $this;
    }

    public function getOrigin(): ?string
    {
        return $this->origin;
    }

    public function setOrigin(string $origin): static
    {
        $this->origin = $origin;

        return $this;
    }

    public function getCapacity(): ?string
    {
        return $this->capacity;
    }

    public function setCapacity(string $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;
        $this->setTotalPrice();

        return $this;
    }

    public function getPromotion(): ?int
    {
        return $this->promotion;
    }

    public function setPromotion(?int $promotion): static
    {
        $this->promotion = $promotion;
        $this->setTotalPrice();

        return $this;
    }

    public function getTotalPrice(): ?int
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(): Static
    {
        $this->totalPrice = $this->calculateTotalPrice();

        return $this;
    }

    public function calculateTotalPrice(): int
    {
        return $this->getPrice() - ($this->getPrice() * ($this->getPromotion() / 100));
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getThreshold(): ?int
    {
        return $this->threshold;
    }

    public function setThreshold(?int $threshold): static
    {
        $this->threshold = $threshold;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): static
    {
        $this->label = $label;

        return $this;
    }
}

templates/layouts/_company_update.html.twig
<div id="companyForm" class="w-full flex flex-col justify-center rounded-lg">
    {{ form_errors(companyForm) }}

    {{ form_start(companyForm) }}
    <div class="grid dashFormBg mb-16 pb-14 rounded-xl">
        <h2 class="text-4xl m-6">Mon Entreprise</h2>
        <div class="flex justify-center gap-28 my-4">
            {{ form_row(companyForm.name) }}
            {{ form_row(companyForm.siret) }}
        </div>
        <div class="flex justify-center gap-28 my-4">
            {{ form_row(companyForm.director_firstname) }}
            {{ form_row(companyForm.director_lastname) }}
        </div>
        <div class="flex justify-center gap-28 my-4">
            {{ form_row(companyForm.address) }}
            {{ form_row(companyForm.zipcode) }}
            {{ form_row(companyForm.city) }}
        </div>
        <div class="flex justify-center gap-28 my-8">
            {{ form_row(companyForm.logo) }}
        </div>
        {% if companyForm.logo%}
            <div class="md:flex justify-center md:mb-6">
                <img id="image" alt="" class="rounded-full w-24 h-24" src="{{ asset("uploaded_img/"~company_logo) }}">
            </div>
        {% endif %}
        <div class="flex justify-center">
            {{ form_row(companyForm.Envoyer) }}
        </div>
    </div>
    {{ form_end(companyForm) }}
</div>

templates/layouts/_dashboard.html.twig
{% include "/layouts/_flash.html.twig" %}
<div id="productForm" class="w-full flex flex-col justify-center rounded-lg hidden">
    {{ form_errors(productForm) }}

    {{ form_start(productForm) }}
    <div class="grid dashFormBg mb-16 pb-14 rounded-xl">
        <h2 class="text-4xl m-6">Produits</h2>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.name) }}
            {{ form_row(productForm.brand) }}
            {{ form_row(productForm.degree_of_alcohol) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.category) }}
            {{ form_row(productForm.style) }}
            {{ form_row(productForm.capacity) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.label) }}
            {{ form_row(productForm.origin) }}
        </div>
    </div>
    <div class="grid dashFormBg mb-16 pb-10 rounded-xl">
        <h2 class="text-4xl m-6">Vente / Gestion</h2>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.price) }}
            {{ form_row(productForm.promotion) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.stock) }}
            {{ form_row(productForm.threshold) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.customer_description) }}
            {{ form_row(productForm.employee_description) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(productForm.Envoyer) }}
        </div>
    </div>
    {{ form_end(productForm) }}

    {# Ajouter le tableau de produits ici #}
</div>

<div id="employeeForm" class="w-full flex flex-col justify-center rounded-lg">

    {{ form_errors(employeeForm) }}
    {{ form_start(employeeForm) }}
    <div class="flex flex-col items-center md:grid dashFormBg mb-16 pb-14 rounded-xl">
        <h2 class="md:text-4xl m-2 md:m-6">Employés</h2>
        <div class="md:flex md:justify-center md:gap-32 md:my-4">
            {{ form_row(employeeForm.firstname) }}
            {{ form_row(employeeForm.lastname) }}
        </div>
        <div class="md:flex md:justify-center md:gap-32 md:my-4">
            {{ form_row(employeeForm.employee_number) }}
        </div>
        <div class="md:flex md:justify-center md:gap-32 md:my-4">
            {{ form_row(employeeForm.Envoyer) }}
        </div>
    </div>
    {{ form_end(employeeForm) }}

    {# Ajouter le tableau des employés ici #}
</div>
<div id="eventForm" class="w-full flex flex-col justify-center rounded-lg hidden">
    {{ form_errors(eventForm) }}

    {{ form_start(eventForm) }}
    <div class="grid dashFormBg mb-16 pb-10 rounded-xl">
        <h2 class="text-4xl m-6">Évènements</h2>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(eventForm.name) }}
            {{ form_row(eventForm.theme) }}
            {{ form_row(eventForm.display_time_period) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(eventForm.start_date) }}
            {{ form_row(eventForm.end_date) }}
        </div>
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(eventForm.start_time) }}
            {{ form_row(eventForm.end_time) }}
        </div>
        <div class="flex justify-center my-4">
            {{ form_row(eventForm.description) }}
        </div>
        <div class="flex justify-center my-4">
            {{ form_row(eventForm.image) }}
        </div>
        {% if eventForm.image%}
            <div class="flex justify-center">
                <img id="image" alt="" class="w-24 h-24" src="{{ asset("assets/img/icon_image.png") }}">
            </div>
        {% endif %}
        <div class="flex justify-center gap-32 my-4">
            {{ form_row(eventForm.Envoyer) }}
        </div>
    </div>
    {{ form_end(eventForm) }}
</div>
{# Ajouter le tableau d'évènements ici #}

templates/layouts/_flash.html.twig
{% if app.flashes is defined %}
{% for label, messages in app.flashes %}
    {% for message in messages %}
        {% if label == "success" %}
            <div class="text-green-500 mt-2">
                {{ message|raw }}
            </div>
        {% else %}
            <div class="text-red-500 mt-2">
                {{ message|raw }}
            </div>
        {% endif %}
    {% endfor %}
{% endfor %}
{% endif %}

templates/layouts/_footer.html.twig
{% block styles_dashboard %}
    <link rel="stylesheet" href="{{ asset("assets/css/dashboard_style.css") }}">
{% endblock %}

<footer class="md:h-28 ">
    <div class="h-12  md:h-28 min-h-full"></div>
</footer>

templates/layouts/_header.html.twig
{% block styles_dashboard %}
    <link rel="stylesheet" href="{{ asset("assets/css/dashboard_style.css") }}">
{% endblock %}

<header class="h-28">
<a href="/dashboard"><img src="{{ asset("assets/img/Logo_StockMinder.png") }}" alt="Logo StockMinder" class="logo md:ml-40 py-2"></a>
</header>

templates/layouts/_menu-category.html.twig
<div class="sm:h-11 lg:w-lg lg:h-16 lg:flex lg:items-center overflow-x-auto lg:mx-auto nav z-10 bg-dun">
    <nav class="sm:h-11 flex items-center">
        <ul class="list-none ml-3.5 uppercase text-base inline whitespace-nowrap lg:text-xl">
            <li class="inline-block px-4 category-link py-1"><a class="" href="#blondes">bières blondes</a></li>
            <li class="inline-block px-4 category-link py-1"><a href="#brunes">bières brunes</a></li>
            <li class="inline-block px-4 category-link py-1"><a href="#blanches">bières blanches</a></li>
            <li class="inline-block px-4 category-link py-1"><a href="#ambrees">bières ambrées</a></li>
            <li class="inline-block px-4 category-link py-1 mr-3.5"><a href="#fruitees">bières fruitées</a></li>
            <li class="inline-block px-4 category-link py-1 mr-3.5"><a href="#sansAlcool">bières sans alcools</a></li>
            <li class="inline-block px-4 category-link py-1 mr-3.5"><a href="#softs">softs</a></li>
        </ul>
    </nav>
</div>

templates/layouts/_menu-event.html.twig
{% if events is not empty %}
<div class="my-event-container overflow-hidden relative h-56 pb-6 lg:w-lg lg:h-72">
    <div class="my-event-container grid grid-cols-1 max-h-52 pb-4 lg:h-64">
        <h2 class="text-2xl uppercase text-center pt-2 lg:text-4xl">Nos prochains événements</h2>
        <div class="my-carousel flex flex-col justify-center mb-6" id="myCarousel">
            {% for event in events %}
                <div class="my-event flex justify-center text-center mx-auto mt-3 w-80 h-38 lg:w-700 lg:h-48 lg:justify-between">
                    <img class="h-20 w-20 flex my-auto lg:w-96 lg:h-48" src="{{ asset('uploaded_img/' ~ event.image) }}" alt="">
                    <div class="my-event-data h-36 flex flex-col p-2 lg:h-48 lg:justify-between">
                        <h3 class="text-lg capitalize lg:text-4xl">{{ event.name }}</h3>
                        <p class="my-event-time text-center text-xs lg:text-lg">Du {{ event.startDate | date('d-m-Y') }}
                            au {{ event.endDate | date('d-m-Y') }}</p>
                        <p class="my-event-time text-center text-xs lg:text-lg">De {{ event.startTime | date('H:i') }}
                            à {{ event.endTime | date('H:i') }}</p>
                        <p class="my-event-theme font-bold capitalize lg:text-xl">{{ event.theme }}</p>
                        <p class="my-event-description text-center text-xs lg:text-lg">{{ event.description }}</p>
                    </div>
                </div>
            {% endfor %}

            <div class="my-indicators-container flex justify-center mt-2">
                <ul class="my-indicators list-none p-0 m-0 flex justify-center" id="indicatorContainer">
                    {% for event in events %}
                        <li class="my-indicator rounded-full h-3 w-3 mx-1 cursor-pointer"></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <img class="my-left-arrow h-6 w-6 my-auto" src="{{ asset('assets/img/Left-arrow.svg') }}" alt="" id="leftArrow">
        <img class="my-right-arrow h-6 w-6 my-auto" src="{{ asset('assets/img/Right-arrow.svg') }}" alt=""
             id="rightArrow">
    </div>
</div>
{% endif  %}

templates/layouts/_menu-filter.html.twig
<nav>
    <div class="flex">
        <img src="{{ asset('assets/img/burger-menu.svg') }}" alt="" class="my-burger burger-hidden my-closed ml-0 mt-3 fixed lg:invisible">
        <div class="my-menu-container menu-hidden w-48 py-3.5 mt-3 rounded-br-lg lg:w-lg">
            {% set action =  null %}
            {% if app.request.get('_route') == 'app_menu' %}
                {% set action = '/carte' %}
            {% elseif app.request.get('_route') == 'app_sell' %}
                {% set action = '/vente' %}
            {% endif %}
            {% if action is not null %}
            <form id="searchTermForm" action="{{ action }}" method="get">
                <div class="flex">
                    {% if searchTerm %}  <input type="text" class="my-search-input w-32 rounded-full p-1 ml-2 focus:font-bold focus:ring-0 border-0" placeholder="Tout voir" name="search">
                    {% else %} <input type="text" class="my-search-input w-32 rounded-full p-1 ml-2 focus:font-bold focus:ring-0 border-0" placeholder="Recherche..." name="search">
                    {% endif %}
                    <button type="submit" id="submitBtn"><img class="mx-4" src="{{ asset('assets/img/search-icon.svg') }}" alt=""></button>
                </div>
            </form>
            {% endif %}
            {{ form_start(form) }}
            <div class="lg:flex lg:flex-col lg:items-center py-2">
                <div class="lg:flex lg:justify-center">
            <div class="my-filter-fields">
                {{ form_row(form.style) }}
            </div>

            <div class="my-filter-fields">
                {{ form_row(form.origin) }}
            </div>

            <div class="my-filter-fields">
                {{ form_row(form.brand) }}
            </div>

            <div class="my-filter-fields my-capacity">
                {{ form_row(form.capacity) }}
            </div>
                </div>
            <div class="my-form-btn flex flex-col items-center w-48 lg:flex-row">
                <div class="pt-2 my-submit lg:mr-2">
                    {{ form_row(form.submit) }}
                </div>

                <div class="pt-2 my-cancel lg:ml-2">
                    {{ form_row(form.button) }}
                </div>
            </div>
                </div>
            {{ form_end(form) }}

        </div>
    </div>
</nav>

templates/layouts/_menu-footer.html.twig
<footer class="my-menu-footer pt-5 pb-3 lg:w-lg lg:mx-auto">
    <div class="grid grid-cols-2">
        <div>
            <h3 class="capitalize text-center text-xs lg:text-4xl">suivez-nous</h3>
            <div class="flex justify-center px-4">
                <img class=" h-7 w-7 mt-2.5 lg:h-12 lg:w-12" src="{{ asset('assets/img/Facebook.svg') }}" alt="">
                <img class="h-7 w-7 mx-2 mt-2.5 lg:h-12 lg:w-12" src="{{ asset('assets/img/Twitter.svg') }}" alt="">
                <img class ="h-7 w-7 mt-2.5 lg:h-12 lg:w-12" src="{{ asset('assets/img/Instagram.svg') }}" alt="">
            </div>
        </div>

        <div>
            <h1 class="text-center capitalize text-xl custom-h1 lg:text-4xl">cheers & beers</h1>
            <p class="text-center capitalize text-xs lg:text-xl">155 rue du dirigeable</p>
            <p class="text-center capitalize text-xs lg:text-xl">13400 aubagne</p>
        </div>
    </div>
    <div>
        {% if route is defined and route == "vente" %}
            <a href="/logout"><img src=" {{ asset("assets/img/logout-persian-orange.png") }}" class="fixed w-6 h-6 left-3 bottom-8" title="Déconnexion"></a>
        {% endif %}
        <p class="text-center text-xs pt-3 lg:text-xl">© Copyright | All rights reserved</p>
    </div>
</footer>

templates/layouts/_menu-legend.html.twig
<div class="my-menu-legend py-5 lg:w-lg lg:mx-auto">
    <h3 class="pb-5 !important text-2xl capitalize text-center lg:text-4xl" id="legend">légende</h3>
    <div class="grid grid-cols-3">
        <div class="mb-3">
            <img class="h-10 w-10 mx-auto lg:h-12 lg:w-12" src="{{ asset('assets/img/Logo_Local.svg') }}" alt="produits locaux">
            <h4 class="text-center mt-1 capitalize">local</h4>
        </div>
        <div class="mb-3">
            <img class="h-10 w-10 mx-auto lg:h-12 lg:w-12" src="{{ asset('assets/img/Logo_Bio.svg') }}" alt="produits biologiques">
            <h4 class="text-center mt-1 capitalize">bio</h4>
        </div>
        <div>
            <img class="h-10 w-10 mx-auto lg:h-12 lg:w-12" src="{{ asset('assets/img/Logo_Gluten_Free.svg') }}" alt="produits sans gluten">
            <h4 class="text-center mt-1 capitalize">sans gluten</h4>
        </div>
    </div>
    <div class="grid grid-cols-3">
        <div class="mb-3">
            <img class="h-10 w-10 mx-auto lg:h-12 lg:w-12" src="{{ asset('assets/img/Logo_Alcohol_Free.svg') }}"
                 alt="produits sans alcool">
            <h4 class="text-center mt-1 capitalize">sans alcool</h4>
        </div>
        <div class="mb-3">
            <img class="h-10 w-10 mx-auto lg:h-12 lg:w-12" src="{{ asset('assets/img/Logo_Lactose.svg') }}"
                 alt="produits contenant du lactose">
            <h4 class="text-center mt-1 capitalize">lactose</h4>
        </div>
        <div class="mb-3">
            <img class="h-10 w-10 mx-auto lg:h-12 lg:w-12" src="{{ asset('assets/img/Logo_Nut.svg') }}"
                 alt="produits contenant de l'arachide">
            <h4 class="text-center mt-1 capitalize">arachide</h4>
        </div>
    </div>
</div>

templates/layouts/_vente-info-modal.html.twig
<!-- info modal---------------------------------------------------------------------------------------------------------------------------------- -->
<div class="my-info-modal grid grid-cols-2">
    <div class="my-hidden my-stock-modal z-30 w-full mx-auto p-2" id="infoModal{{ loop.index0 }}" aria-labelledby="Description détaillée"
         role="dialog"
         aria-modal="true">
        <div class="z-40 col-start-1 col-end-2 items-center transform overflow-hidden rounded-xl my-modal-border text-center shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
            <div class="my-modal-description px-4 p-2">
                <div class="flex justify-between">
                    <img class="h-7 w-7 my-1" src="{{ asset('assets/img/info.svg') }}" alt="">
                    <h2 class="text-lg">Description détaillée</h2>
                    <img class="h-7 w-7 my-1" src="{{ asset('assets/img/close-cross.svg') }}"
                         onclick="closeInfoModal(this, {{ loop.index0 }})" alt="">
                </div>
                <h3 class="capitalize text-sm">{{ product.name }}</h3>
                <p class="text-lg">{{ product.employeeDescription }}</p>
            </div>
        </div>
    </div>
</div>

<!-- end info modal--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->